////////////////////////////////////////////////////////////////////////////////
//
// Filename:	./regdefs.h
// {{{
// Project:	AXI DMA Check: A utility to measure AXI DMA speeds
//
// DO NOT EDIT THIS FILE!
// Computer Generated: This file is computer generated by AUTOFPGA. DO NOT EDIT.
// DO NOT EDIT THIS FILE!
//
// CmdLine:	/home/dan/work/rnd/opencores/autofpga/trunk/sw/autofpga /home/dan/work/rnd/opencores/autofpga/trunk/sw/autofpga -d autofpga.dbg -o ./ global.txt axibus.txt axiram.txt axidma.txt aximm2s.txt axis2mm.txt controlbus.txt streamsink.txt streamsrc.txt vibus.txt zipaxi.txt axiconsole.txt mem_bkram_only.txt mm2sperf.txt s2mmperf.txt dmaperf.txt cpuperf.txt ramperf.txt
//
// Creator:	Dan Gisselquist, Ph.D.
//		Gisselquist Technology, LLC
//
////////////////////////////////////////////////////////////////////////////////
// }}}
// Copyright (C) 2020-2021, Gisselquist Technology, LLC
// {{{
// This program is free software (firmware): you can redistribute it and/or
// modify it under the terms of the GNU General Public License as published
// by the Free Software Foundation, either version 3 of the License, or (at
// your option) any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTIBILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program.  (It's in the $(ROOT)/doc directory.  Run make with no
// target there if the PDF file isn't present.)  If not, see
// <http://www.gnu.org/licenses/> for a copy.
// }}}
// License:	GPL, v3, as defined and found on www.gnu.org,
// {{{
//		http://www.gnu.org/licenses/gpl.html
//
////////////////////////////////////////////////////////////////////////////////
//
// }}}
#ifndef	REGDEFS_H
#define	REGDEFS_H


//
// The @REGDEFS.H.INCLUDE tag
//
// @REGDEFS.H.INCLUDE for masters
// @REGDEFS.H.INCLUDE for peripherals
// And finally any master REGDEFS.H.INCLUDE tags
// End of definitions from REGDEFS.H.INCLUDE


//
// Register address definitions, from @REGS.#d
//
// CONSOLE registers
#define	R_CONSOLE_FIFO      	0x00800004	// 00800000, wbregs names: UFIFO
#define	R_CONSOLE_UARTRX    	0x00800008	// 00800000, wbregs names: RX
#define	R_CONSOLE_UARTTX    	0x0080000c	// 00800000, wbregs names: TX
// AXIL Peripheral set
#define	R_AXILP             	0x00800200	// 00800200, wbregs names: axilp
#define	R_PIC               	0x00800204	// 00800200, wbregs names: pic
#define	R_WDT               	0x00800208	// 00800200, wbregs names: watchdog
#define	R_TIMA              	0x00800210	// 00800200, wbregs names: timera
#define	R_TIMB              	0x00800214	// 00800200, wbregs names: timerb
#define	R_TIMC              	0x00800218	// 00800200, wbregs names: timerc
#define	R_STREAMSINK_BEATS  	0x00800400	// 00800400, wbregs names: BEATS
#define	R_STREAMSINK_PACKETS	0x00800404	// 00800400, wbregs names: PACKETS
#define	R_STREAMSINK_CLOCKS 	0x00800408	// 00800400, wbregs names: CLOCKS
#define	R_AXIDMACTRL        	0x00800440	// 00800440, wbregs names: AXIDMACTRL
#define	R_AXIDMASRCLO       	0x00800448	// 00800440, wbregs names: AXIDMASRCLO
#define	R_AXIDMASRCHI       	0x0080044c	// 00800440, wbregs names: AXIDMASRCHI
#define	R_AXIDMADSTLO       	0x00800450	// 00800440, wbregs names: AXIDMADSTLO
#define	R_AXIDMADSTHI       	0x00800454	// 00800440, wbregs names: AXIDMADSTHI
#define	R_AXIDMALENLO       	0x00800458	// 00800440, wbregs names: AXIDMALENLO
#define	R_AXIDMALENHI       	0x0080045c	// 00800440, wbregs names: AXIDMALENHI
// AXI MM2S registers
#define	R_MM2SCTRL          	0x00800480	// 00800480, wbregs names: MM2SCTRL
#define	R_MM2SADDRLO        	0x00800488	// 00800480, wbregs names: MM2SADDRLO
#define	R_MM2SADDRHI        	0x0080048c	// 00800480, wbregs names: MM2SADDRHI
#define	R_MM2SLENLO         	0x00800498	// 00800480, wbregs names: MM2SLENLO
#define	R_MM2SLENHI         	0x0080049c	// 00800480, wbregs names: MM2SLENHI
#define	R_S2MMCTRL          	0x008004c0	// 008004c0, wbregs names: S2MMCTRL
#define	R_S2MMADDRLO        	0x008004d0	// 008004c0, wbregs names: S2MMADDRLO
#define	R_S2MMADDRHI        	0x008004d4	// 008004c0, wbregs names: S2MMADDRHI
#define	R_S2MMLENLO         	0x008004d8	// 008004c0, wbregs names: S2MMLENLO
#define	R_S2MMLENHI         	0x008004dc	// 008004c0, wbregs names: S2MMLENHI
//
// AXI Performance monitor for CPUDPERF
//

#define	R_CPUDPERFACTIVE    	0x00800500	// 00800500, wbregs names: CPUDPERFACTIVE
#define	R_CPUDPERFBURSTSZ   	0x00800504	// 00800500, wbregs names: CPUDPERFBURSTSZ
#define	R_CPUDPERFWRIDLES   	0x00800508	// 00800500, wbregs names: CPUDPERFWRIDLES
#define	R_CPUDPERFAWRBURSTS 	0x0080050c	// 00800500, wbregs names: CPUDPERFAWRBURSTS
#define	R_CPUDPERFWRBEATS   	0x00800510	// 00800500, wbregs names: CPUDPERFWRBEATS
#define	R_CPUDPERFAWBYTES   	0x00800514	// 00800500, wbregs names: CPUDPERFAWBYTES
#define	R_CPUDPERFWBYTES    	0x00800518	// 00800500, wbregs names: CPUDPERFWBYTES
#define	R_CPUDPERFWRSLOWD   	0x0080051c	// 00800500, wbregs names: CPUDPERFWRSLOWD
#define	R_CPUDPERFWRSTALLS  	0x00800520	// 00800500, wbregs names: CPUDPERFWRSTALLS
#define	R_CPUDPERFWRADDRLAG 	0x00800524	// 00800500, wbregs names: CPUDPERFWRADDRLAG
#define	R_CPUDPERFWRDATALAG 	0x00800528	// 00800500, wbregs names: CPUDPERFWRDATALAG
#define	R_CPUDPERFAWREARLY  	0x0080052c	// 00800500, wbregs names: CPUDPERFAWREARLY
#define	R_CPUDPERFWREARLYD  	0x00800530	// 00800500, wbregs names: CPUDPERFWREARLYD
#define	R_CPUDPERFAWSTALL   	0x00800534	// 00800500, wbregs names: CPUDPERFAWSTALL
#define	R_CPUDPERFEARLYST   	0x00800538	// 00800500, wbregs names: CPUDPERFEARLYST
#define	R_CPUDPERFWRBLAGS   	0x0080053c	// 00800500, wbregs names: CPUDPERFWRBLAGS
#define	R_CPUDPERFWRBSTALL  	0x00800540	// 00800500, wbregs names: CPUDPERFWRBSTALL
#define	R_CPUDPERFWRBEND    	0x00800544	// 00800500, wbregs names: CPUDPERFWRBEND
#define	R_CPUDPERFWRBIAS    	0x00800548	// 00800500, wbregs names: CPUDPERFWRBIAS
#define	R_CPUDPERFWUNUSED   	0x0080054c	// 00800500, wbregs names: CPUDPERFWUNUSED
#define	R_CPUDPERFRDIDLES   	0x00800550	// 00800500, wbregs names: CPUDPERFRDIDLES
#define	R_CPUDPERFRDMAXB    	0x00800554	// 00800500, wbregs names: CPUDPERFRDMAXB
#define	R_CPUDPERFRDBURSTS  	0x00800558	// 00800500, wbregs names: CPUDPERFRDBURSTS
#define	R_CPUDPERFRDBEATS   	0x0080055c	// 00800500, wbregs names: CPUDPERFRDBEATS
#define	R_CPUDPERFRDBYTES   	0x00800560	// 00800500, wbregs names: CPUDPERFRDBYTES
#define	R_CPUDPERFRDARCYCLES	0x00800564	// 00800500, wbregs names: CPUDPERFRDARSCYCLES
#define	R_CPUDPERFRDARSTALLS	0x00800568	// 00800500, wbregs names: CPUDPERFRDARSTALLS
#define	R_CPUDPERFRDRSTALLS 	0x0080056c	// 00800500, wbregs names: CPUDPERFRDRSTALLS
#define	R_CPUDPERFRDLAG     	0x00800570	// 00800500, wbregs names: CPUDPERFRDLAG
#define	R_CPUDPERFRDSLOW    	0x00800574	// 00800500, wbregs names: CPUDPERFRDSLOW
#define	R_CPUDPERFRDFIRSTLAG	0x00800578	// 00800500, wbregs names: CPUDPERFRDFIRSTLAG
#define	R_CPUDPERFCONTROL   	0x0080057c	// 00800500, wbregs names: CPUDPERFCONTROL
//
// AXI Performance monitor for CPUIPERF
//

#define	R_CPUIPERFACTIVE    	0x00800580	// 00800580, wbregs names: CPUIPERFACTIVE
#define	R_CPUIPERFBURSTSZ   	0x00800584	// 00800580, wbregs names: CPUIPERFBURSTSZ
#define	R_CPUIPERFWRIDLES   	0x00800588	// 00800580, wbregs names: CPUIPERFWRIDLES
#define	R_CPUIPERFAWRBURSTS 	0x0080058c	// 00800580, wbregs names: CPUIPERFAWRBURSTS
#define	R_CPUIPERFWRBEATS   	0x00800590	// 00800580, wbregs names: CPUIPERFWRBEATS
#define	R_CPUIPERFAWBYTES   	0x00800594	// 00800580, wbregs names: CPUIPERFAWBYTES
#define	R_CPUIPERFWBYTES    	0x00800598	// 00800580, wbregs names: CPUIPERFWBYTES
#define	R_CPUIPERFWRSLOWD   	0x0080059c	// 00800580, wbregs names: CPUIPERFWRSLOWD
#define	R_CPUIPERFWRSTALLS  	0x008005a0	// 00800580, wbregs names: CPUIPERFWRSTALLS
#define	R_CPUIPERFWRADDRLAG 	0x008005a4	// 00800580, wbregs names: CPUIPERFWRADDRLAG
#define	R_CPUIPERFWRDATALAG 	0x008005a8	// 00800580, wbregs names: CPUIPERFWRDATALAG
#define	R_CPUIPERFAWREARLY  	0x008005ac	// 00800580, wbregs names: CPUIPERFAWREARLY
#define	R_CPUIPERFWREARLYD  	0x008005b0	// 00800580, wbregs names: CPUIPERFWREARLYD
#define	R_CPUIPERFAWSTALL   	0x008005b4	// 00800580, wbregs names: CPUIPERFAWSTALL
#define	R_CPUIPERFEARLYST   	0x008005b8	// 00800580, wbregs names: CPUIPERFEARLYST
#define	R_CPUIPERFWRBLAGS   	0x008005bc	// 00800580, wbregs names: CPUIPERFWRBLAGS
#define	R_CPUIPERFWRBSTALL  	0x008005c0	// 00800580, wbregs names: CPUIPERFWRBSTALL
#define	R_CPUIPERFWRBEND    	0x008005c4	// 00800580, wbregs names: CPUIPERFWRBEND
#define	R_CPUIPERFWRBIAS    	0x008005c8	// 00800580, wbregs names: CPUIPERFWRBIAS
#define	R_CPUIPERFWUNUSED   	0x008005cc	// 00800580, wbregs names: CPUIPERFWUNUSED
#define	R_CPUIPERFRDIDLES   	0x008005d0	// 00800580, wbregs names: CPUIPERFRDIDLES
#define	R_CPUIPERFRDMAXB    	0x008005d4	// 00800580, wbregs names: CPUIPERFRDMAXB
#define	R_CPUIPERFRDBURSTS  	0x008005d8	// 00800580, wbregs names: CPUIPERFRDBURSTS
#define	R_CPUIPERFRDBEATS   	0x008005dc	// 00800580, wbregs names: CPUIPERFRDBEATS
#define	R_CPUIPERFRDBYTES   	0x008005e0	// 00800580, wbregs names: CPUIPERFRDBYTES
#define	R_CPUIPERFRDARCYCLES	0x008005e4	// 00800580, wbregs names: CPUIPERFRDARSCYCLES
#define	R_CPUIPERFRDARSTALLS	0x008005e8	// 00800580, wbregs names: CPUIPERFRDARSTALLS
#define	R_CPUIPERFRDRSTALLS 	0x008005ec	// 00800580, wbregs names: CPUIPERFRDRSTALLS
#define	R_CPUIPERFRDLAG     	0x008005f0	// 00800580, wbregs names: CPUIPERFRDLAG
#define	R_CPUIPERFRDSLOW    	0x008005f4	// 00800580, wbregs names: CPUIPERFRDSLOW
#define	R_CPUIPERFRDFIRSTLAG	0x008005f8	// 00800580, wbregs names: CPUIPERFRDFIRSTLAG
#define	R_CPUIPERFCONTROL   	0x008005fc	// 00800580, wbregs names: CPUIPERFCONTROL
//
// AXI Performance monitor for DMAPERF
//

#define	R_DMAPERFACTIVE     	0x00800600	// 00800600, wbregs names: DMAPERFACTIVE
#define	R_DMAPERFBURSTSZ    	0x00800604	// 00800600, wbregs names: DMAPERFBURSTSZ
#define	R_DMAPERFWRIDLES    	0x00800608	// 00800600, wbregs names: DMAPERFWRIDLES
#define	R_DMAPERFAWRBURSTS  	0x0080060c	// 00800600, wbregs names: DMAPERFAWRBURSTS
#define	R_DMAPERFWRBEATS    	0x00800610	// 00800600, wbregs names: DMAPERFWRBEATS
#define	R_DMAPERFAWBYTES    	0x00800614	// 00800600, wbregs names: DMAPERFAWBYTES
#define	R_DMAPERFWBYTES     	0x00800618	// 00800600, wbregs names: DMAPERFWBYTES
#define	R_DMAPERFWRSLOWD    	0x0080061c	// 00800600, wbregs names: DMAPERFWRSLOWD
#define	R_DMAPERFWRSTALLS   	0x00800620	// 00800600, wbregs names: DMAPERFWRSTALLS
#define	R_DMAPERFWRADDRLAG  	0x00800624	// 00800600, wbregs names: DMAPERFWRADDRLAG
#define	R_DMAPERFWRDATALAG  	0x00800628	// 00800600, wbregs names: DMAPERFWRDATALAG
#define	R_DMAPERFAWREARLY   	0x0080062c	// 00800600, wbregs names: DMAPERFAWREARLY
#define	R_DMAPERFWREARLYD   	0x00800630	// 00800600, wbregs names: DMAPERFWREARLYD
#define	R_DMAPERFAWSTALL    	0x00800634	// 00800600, wbregs names: DMAPERFAWSTALL
#define	R_DMAPERFEARLYST    	0x00800638	// 00800600, wbregs names: DMAPERFEARLYST
#define	R_DMAPERFWRBLAGS    	0x0080063c	// 00800600, wbregs names: DMAPERFWRBLAGS
#define	R_DMAPERFWRBSTALL   	0x00800640	// 00800600, wbregs names: DMAPERFWRBSTALL
#define	R_DMAPERFWRBEND     	0x00800644	// 00800600, wbregs names: DMAPERFWRBEND
#define	R_DMAPERFWRBIAS     	0x00800648	// 00800600, wbregs names: DMAPERFWRBIAS
#define	R_DMAPERFWUNUSED    	0x0080064c	// 00800600, wbregs names: DMAPERFWUNUSED
#define	R_DMAPERFRDIDLES    	0x00800650	// 00800600, wbregs names: DMAPERFRDIDLES
#define	R_DMAPERFRDMAXB     	0x00800654	// 00800600, wbregs names: DMAPERFRDMAXB
#define	R_DMAPERFRDBURSTS   	0x00800658	// 00800600, wbregs names: DMAPERFRDBURSTS
#define	R_DMAPERFRDBEATS    	0x0080065c	// 00800600, wbregs names: DMAPERFRDBEATS
#define	R_DMAPERFRDBYTES    	0x00800660	// 00800600, wbregs names: DMAPERFRDBYTES
#define	R_DMAPERFRDARCYCLES 	0x00800664	// 00800600, wbregs names: DMAPERFRDARSCYCLES
#define	R_DMAPERFRDARSTALLS 	0x00800668	// 00800600, wbregs names: DMAPERFRDARSTALLS
#define	R_DMAPERFRDRSTALLS  	0x0080066c	// 00800600, wbregs names: DMAPERFRDRSTALLS
#define	R_DMAPERFRDLAG      	0x00800670	// 00800600, wbregs names: DMAPERFRDLAG
#define	R_DMAPERFRDSLOW     	0x00800674	// 00800600, wbregs names: DMAPERFRDSLOW
#define	R_DMAPERFRDFIRSTLAG 	0x00800678	// 00800600, wbregs names: DMAPERFRDFIRSTLAG
#define	R_DMAPERFCONTROL    	0x0080067c	// 00800600, wbregs names: DMAPERFCONTROL
//
// AXI Performance monitor for MM2SPERF
//

#define	R_MM2SPERFACTIVE    	0x00800680	// 00800680, wbregs names: MM2SPERFACTIVE
#define	R_MM2SPERFBURSTSZ   	0x00800684	// 00800680, wbregs names: MM2SPERFBURSTSZ
#define	R_MM2SPERFWRIDLES   	0x00800688	// 00800680, wbregs names: MM2SPERFWRIDLES
#define	R_MM2SPERFAWRBURSTS 	0x0080068c	// 00800680, wbregs names: MM2SPERFAWRBURSTS
#define	R_MM2SPERFWRBEATS   	0x00800690	// 00800680, wbregs names: MM2SPERFWRBEATS
#define	R_MM2SPERFAWBYTES   	0x00800694	// 00800680, wbregs names: MM2SPERFAWBYTES
#define	R_MM2SPERFWBYTES    	0x00800698	// 00800680, wbregs names: MM2SPERFWBYTES
#define	R_MM2SPERFWRSLOWD   	0x0080069c	// 00800680, wbregs names: MM2SPERFWRSLOWD
#define	R_MM2SPERFWRSTALLS  	0x008006a0	// 00800680, wbregs names: MM2SPERFWRSTALLS
#define	R_MM2SPERFWRADDRLAG 	0x008006a4	// 00800680, wbregs names: MM2SPERFWRADDRLAG
#define	R_MM2SPERFWRDATALAG 	0x008006a8	// 00800680, wbregs names: MM2SPERFWRDATALAG
#define	R_MM2SPERFAWREARLY  	0x008006ac	// 00800680, wbregs names: MM2SPERFAWREARLY
#define	R_MM2SPERFWREARLYD  	0x008006b0	// 00800680, wbregs names: MM2SPERFWREARLYD
#define	R_MM2SPERFAWSTALL   	0x008006b4	// 00800680, wbregs names: MM2SPERFAWSTALL
#define	R_MM2SPERFEARLYST   	0x008006b8	// 00800680, wbregs names: MM2SPERFEARLYST
#define	R_MM2SPERFWRBLAGS   	0x008006bc	// 00800680, wbregs names: MM2SPERFWRBLAGS
#define	R_MM2SPERFWRBSTALL  	0x008006c0	// 00800680, wbregs names: MM2SPERFWRBSTALL
#define	R_MM2SPERFWRBEND    	0x008006c4	// 00800680, wbregs names: MM2SPERFWRBEND
#define	R_MM2SPERFWRBIAS    	0x008006c8	// 00800680, wbregs names: MM2SPERFWRBIAS
#define	R_MM2SPERFWUNUSED   	0x008006cc	// 00800680, wbregs names: MM2SPERFWUNUSED
#define	R_MM2SPERFRDIDLES   	0x008006d0	// 00800680, wbregs names: MM2SPERFRDIDLES
#define	R_MM2SPERFRDMAXB    	0x008006d4	// 00800680, wbregs names: MM2SPERFRDMAXB
#define	R_MM2SPERFRDBURSTS  	0x008006d8	// 00800680, wbregs names: MM2SPERFRDBURSTS
#define	R_MM2SPERFRDBEATS   	0x008006dc	// 00800680, wbregs names: MM2SPERFRDBEATS
#define	R_MM2SPERFRDBYTES   	0x008006e0	// 00800680, wbregs names: MM2SPERFRDBYTES
#define	R_MM2SPERFRDARCYCLES	0x008006e4	// 00800680, wbregs names: MM2SPERFRDARSCYCLES
#define	R_MM2SPERFRDARSTALLS	0x008006e8	// 00800680, wbregs names: MM2SPERFRDARSTALLS
#define	R_MM2SPERFRDRSTALLS 	0x008006ec	// 00800680, wbregs names: MM2SPERFRDRSTALLS
#define	R_MM2SPERFRDLAG     	0x008006f0	// 00800680, wbregs names: MM2SPERFRDLAG
#define	R_MM2SPERFRDSLOW    	0x008006f4	// 00800680, wbregs names: MM2SPERFRDSLOW
#define	R_MM2SPERFRDFIRSTLAG	0x008006f8	// 00800680, wbregs names: MM2SPERFRDFIRSTLAG
#define	R_MM2SPERFCONTROL   	0x008006fc	// 00800680, wbregs names: MM2SPERFCONTROL
//
// AXI Performance monitor for RAMPERF
//

#define	R_RAMPERFACTIVE     	0x00800700	// 00800700, wbregs names: RAMPERFACTIVE
#define	R_RAMPERFBURSTSZ    	0x00800704	// 00800700, wbregs names: RAMPERFBURSTSZ
#define	R_RAMPERFWRIDLES    	0x00800708	// 00800700, wbregs names: RAMPERFWRIDLES
#define	R_RAMPERFAWRBURSTS  	0x0080070c	// 00800700, wbregs names: RAMPERFAWRBURSTS
#define	R_RAMPERFWRBEATS    	0x00800710	// 00800700, wbregs names: RAMPERFWRBEATS
#define	R_RAMPERFAWBYTES    	0x00800714	// 00800700, wbregs names: RAMPERFAWBYTES
#define	R_RAMPERFWBYTES     	0x00800718	// 00800700, wbregs names: RAMPERFWBYTES
#define	R_RAMPERFWRSLOWD    	0x0080071c	// 00800700, wbregs names: RAMPERFWRSLOWD
#define	R_RAMPERFWRSTALLS   	0x00800720	// 00800700, wbregs names: RAMPERFWRSTALLS
#define	R_RAMPERFWRADDRLAG  	0x00800724	// 00800700, wbregs names: RAMPERFWRADDRLAG
#define	R_RAMPERFWRDATALAG  	0x00800728	// 00800700, wbregs names: RAMPERFWRDATALAG
#define	R_RAMPERFAWREARLY   	0x0080072c	// 00800700, wbregs names: RAMPERFAWREARLY
#define	R_RAMPERFWREARLYD   	0x00800730	// 00800700, wbregs names: RAMPERFWREARLYD
#define	R_RAMPERFAWSTALL    	0x00800734	// 00800700, wbregs names: RAMPERFAWSTALL
#define	R_RAMPERFEARLYST    	0x00800738	// 00800700, wbregs names: RAMPERFEARLYST
#define	R_RAMPERFWRBLAGS    	0x0080073c	// 00800700, wbregs names: RAMPERFWRBLAGS
#define	R_RAMPERFWRBSTALL   	0x00800740	// 00800700, wbregs names: RAMPERFWRBSTALL
#define	R_RAMPERFWRBEND     	0x00800744	// 00800700, wbregs names: RAMPERFWRBEND
#define	R_RAMPERFWRBIAS     	0x00800748	// 00800700, wbregs names: RAMPERFWRBIAS
#define	R_RAMPERFWUNUSED    	0x0080074c	// 00800700, wbregs names: RAMPERFWUNUSED
#define	R_RAMPERFRDIDLES    	0x00800750	// 00800700, wbregs names: RAMPERFRDIDLES
#define	R_RAMPERFRDMAXB     	0x00800754	// 00800700, wbregs names: RAMPERFRDMAXB
#define	R_RAMPERFRDBURSTS   	0x00800758	// 00800700, wbregs names: RAMPERFRDBURSTS
#define	R_RAMPERFRDBEATS    	0x0080075c	// 00800700, wbregs names: RAMPERFRDBEATS
#define	R_RAMPERFRDBYTES    	0x00800760	// 00800700, wbregs names: RAMPERFRDBYTES
#define	R_RAMPERFRDARCYCLES 	0x00800764	// 00800700, wbregs names: RAMPERFRDARSCYCLES
#define	R_RAMPERFRDARSTALLS 	0x00800768	// 00800700, wbregs names: RAMPERFRDARSTALLS
#define	R_RAMPERFRDRSTALLS  	0x0080076c	// 00800700, wbregs names: RAMPERFRDRSTALLS
#define	R_RAMPERFRDLAG      	0x00800770	// 00800700, wbregs names: RAMPERFRDLAG
#define	R_RAMPERFRDSLOW     	0x00800774	// 00800700, wbregs names: RAMPERFRDSLOW
#define	R_RAMPERFRDFIRSTLAG 	0x00800778	// 00800700, wbregs names: RAMPERFRDFIRSTLAG
#define	R_RAMPERFCONTROL    	0x0080077c	// 00800700, wbregs names: RAMPERFCONTROL
//
// AXI Performance monitor for S2MMPERF
//

#define	R_S2MMPERFACTIVE    	0x00800780	// 00800780, wbregs names: S2MMPERFACTIVE
#define	R_S2MMPERFBURSTSZ   	0x00800784	// 00800780, wbregs names: S2MMPERFBURSTSZ
#define	R_S2MMPERFWRIDLES   	0x00800788	// 00800780, wbregs names: S2MMPERFWRIDLES
#define	R_S2MMPERFAWRBURSTS 	0x0080078c	// 00800780, wbregs names: S2MMPERFAWRBURSTS
#define	R_S2MMPERFWRBEATS   	0x00800790	// 00800780, wbregs names: S2MMPERFWRBEATS
#define	R_S2MMPERFAWBYTES   	0x00800794	// 00800780, wbregs names: S2MMPERFAWBYTES
#define	R_S2MMPERFWBYTES    	0x00800798	// 00800780, wbregs names: S2MMPERFWBYTES
#define	R_S2MMPERFWRSLOWD   	0x0080079c	// 00800780, wbregs names: S2MMPERFWRSLOWD
#define	R_S2MMPERFWRSTALLS  	0x008007a0	// 00800780, wbregs names: S2MMPERFWRSTALLS
#define	R_S2MMPERFWRADDRLAG 	0x008007a4	// 00800780, wbregs names: S2MMPERFWRADDRLAG
#define	R_S2MMPERFWRDATALAG 	0x008007a8	// 00800780, wbregs names: S2MMPERFWRDATALAG
#define	R_S2MMPERFAWREARLY  	0x008007ac	// 00800780, wbregs names: S2MMPERFAWREARLY
#define	R_S2MMPERFWREARLYD  	0x008007b0	// 00800780, wbregs names: S2MMPERFWREARLYD
#define	R_S2MMPERFAWSTALL   	0x008007b4	// 00800780, wbregs names: S2MMPERFAWSTALL
#define	R_S2MMPERFEARLYST   	0x008007b8	// 00800780, wbregs names: S2MMPERFEARLYST
#define	R_S2MMPERFWRBLAGS   	0x008007bc	// 00800780, wbregs names: S2MMPERFWRBLAGS
#define	R_S2MMPERFWRBSTALL  	0x008007c0	// 00800780, wbregs names: S2MMPERFWRBSTALL
#define	R_S2MMPERFWRBEND    	0x008007c4	// 00800780, wbregs names: S2MMPERFWRBEND
#define	R_S2MMPERFWRBIAS    	0x008007c8	// 00800780, wbregs names: S2MMPERFWRBIAS
#define	R_S2MMPERFWUNUSED   	0x008007cc	// 00800780, wbregs names: S2MMPERFWUNUSED
#define	R_S2MMPERFRDIDLES   	0x008007d0	// 00800780, wbregs names: S2MMPERFRDIDLES
#define	R_S2MMPERFRDMAXB    	0x008007d4	// 00800780, wbregs names: S2MMPERFRDMAXB
#define	R_S2MMPERFRDBURSTS  	0x008007d8	// 00800780, wbregs names: S2MMPERFRDBURSTS
#define	R_S2MMPERFRDBEATS   	0x008007dc	// 00800780, wbregs names: S2MMPERFRDBEATS
#define	R_S2MMPERFRDBYTES   	0x008007e0	// 00800780, wbregs names: S2MMPERFRDBYTES
#define	R_S2MMPERFRDARCYCLES	0x008007e4	// 00800780, wbregs names: S2MMPERFRDARSCYCLES
#define	R_S2MMPERFRDARSTALLS	0x008007e8	// 00800780, wbregs names: S2MMPERFRDARSTALLS
#define	R_S2MMPERFRDRSTALLS 	0x008007ec	// 00800780, wbregs names: S2MMPERFRDRSTALLS
#define	R_S2MMPERFRDLAG     	0x008007f0	// 00800780, wbregs names: S2MMPERFRDLAG
#define	R_S2MMPERFRDSLOW    	0x008007f4	// 00800780, wbregs names: S2MMPERFRDSLOW
#define	R_S2MMPERFRDFIRSTLAG	0x008007f8	// 00800780, wbregs names: S2MMPERFRDFIRSTLAG
#define	R_S2MMPERFCONTROL   	0x008007fc	// 00800780, wbregs names: S2MMPERFCONTROL
#define	R_AXIRAM            	0x01000000	// 01000000, wbregs names: AXIRAM, RAM
// ZipCPU control/debug registers
#define	R_ZIPCTRL           	0x02000080	// 02000000, wbregs names: CPU, ZIPCTRL
#define	R_ZIPREGS           	0x02000000	// 02000000, wbregs names: ZIPREGS
#define	R_ZIPS0             	0x02000000	// 02000000, wbregs names: SR0
#define	R_ZIPS1             	0x02000004	// 02000000, wbregs names: SR1
#define	R_ZIPS2             	0x02000008	// 02000000, wbregs names: SR2
#define	R_ZIPS3             	0x0200000c	// 02000000, wbregs names: SR3
#define	R_ZIPS4             	0x02000010	// 02000000, wbregs names: SR4
#define	R_ZIPS5             	0x02000014	// 02000000, wbregs names: SR5
#define	R_ZIPS6             	0x02000018	// 02000000, wbregs names: SR6
#define	R_ZIPS7             	0x0200001c	// 02000000, wbregs names: SR7
#define	R_ZIPS8             	0x02000020	// 02000000, wbregs names: SR8
#define	R_ZIPS9             	0x02000024	// 02000000, wbregs names: SR9
#define	R_ZIPS10            	0x02000028	// 02000000, wbregs names: SR10
#define	R_ZIPS11            	0x0200002c	// 02000000, wbregs names: SR11
#define	R_ZIPS12            	0x02000030	// 02000000, wbregs names: SR12
#define	R_ZIPSSP            	0x02000034	// 02000000, wbregs names: SSP, SR13
#define	R_ZIPCC             	0x02000038	// 02000000, wbregs names: ZIPCC, CC, SCC, SR14
#define	R_ZIPPC             	0x0200003c	// 02000000, wbregs names: ZIPPC, PC, SPC, SR15
#define	R_ZIPUSER           	0x02000040	// 02000000, wbregs names: ZIPUSER
#define	R_ZIPU0             	0x02000040	// 02000000, wbregs names: UR0
#define	R_ZIPU1             	0x02000044	// 02000000, wbregs names: UR1
#define	R_ZIPU2             	0x02000048	// 02000000, wbregs names: UR2
#define	R_ZIPU3             	0x0200004c	// 02000000, wbregs names: UR3
#define	R_ZIPU4             	0x02000050	// 02000000, wbregs names: UR4
#define	R_ZIPU5             	0x02000054	// 02000000, wbregs names: UR5
#define	R_ZIPU6             	0x02000058	// 02000000, wbregs names: UR6
#define	R_ZIPU7             	0x0200005c	// 02000000, wbregs names: UR7
#define	R_ZIPU8             	0x02000060	// 02000000, wbregs names: UR8
#define	R_ZIPU9             	0x02000064	// 02000000, wbregs names: UR9
#define	R_ZIPU10            	0x02000068	// 02000000, wbregs names: SR10
#define	R_ZIPU11            	0x0200006c	// 02000000, wbregs names: SR11
#define	R_ZIPU12            	0x02000070	// 02000000, wbregs names: SR12
#define	R_ZIPUSP            	0x02000074	// 02000000, wbregs names: USP, UR13
#define	R_ZIPUCC            	0x02000078	// 02000000, wbregs names: ZIPUCC, UCC
#define	R_ZIPUPC            	0x0200007c	// 02000000, wbregs names: ZIPUPC, UPC
#define	R_ZIPSYSTEM         	0x02000100	// 02000000, wbregs names: ZIPSYSTEM, ZIPSYS


//
// The @REGDEFS.H.DEFNS tag
//
// @REGDEFS.H.DEFNS for masters
#define	BAUDRATE	1000000
// @REGDEFS.H.DEFNS for peripherals
// @REGDEFS.H.DEFNS at the top level
// End of definitions from REGDEFS.H.DEFNS
//
// The @REGDEFS.H.INSERT tag
//
// @REGDEFS.H.INSERT for masters
// @REGDEFS.H.INSERT for peripherals

#define	CPU_GO		0x0000
#define	CPU_RESET	0x0040
#define	CPU_INT		0x0080
#define	CPU_STEP	0x0100
#define	CPU_STALL	0x0200
#define	CPU_HALT	0x0400
#define	CPU_CLRCACHE	0x0800

#define	RESET_ADDRESS	0x01000000


#define	RAMSIZE	(1u<<24)

// @REGDEFS.H.INSERT from the top level
typedef	struct {
	unsigned	m_addr;
	const char	*m_name;
} REGNAME;

extern	const	REGNAME	*bregs;
extern	const	int	NREGS;
// #define	NREGS	(sizeof(bregs)/sizeof(bregs[0]))

extern	unsigned	addrdecode(const char *v);
extern	const	char *addrname(const unsigned v);
// End of definitions from REGDEFS.H.INSERT


#endif	// REGDEFS_H
